services:
  - type: web
    name: chat-with-strangers-3
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: lts
